baseURL = "https://ncldaniela.github.io"
languageCode = "en-us"
title = "Daniela Liliana Nicolae"
theme = "hugo-theme-learn"

# Enable search
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Author of the site, will be used in meta information
  author = "Daniela Liliana Nicolae"
  # Description of the site, will be used in meta information
  description = "Site pentru resurse legate de programare si informatica in general."
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"